name: "[DLS] [U22/U24] Build weekly cache imgs"
run-name: "[DLS] [U22/U24] Build weekly cache imgs"
on:
  schedule:
    - cron: '0 5 * * MON' # 5:00 UTC each Monday
  workflow_dispatch:
permissions: {}
env:
  dlstreamer-version: "2026.0.0"
  DLS_REL_PATH: "./dlstreamer-repo"

jobs:
  build-dls-deb-img:
    name: Build DLS ${{ matrix.ubuntu_version }} .deb and deb img
    runs-on: dlstreamer
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - path_dockerfile: ./dlstreamer-repo/docker/ubuntu/ubuntu22.Dockerfile
            ubuntu_version: ubuntu22
          - path_dockerfile: ./dlstreamer-repo/docker/ubuntu/ubuntu24.Dockerfile
            ubuntu_version: ubuntu24
    steps:
      - name: Check out dlstreamer repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2
        with:
          persist-credentials: false
          path: dlstreamer-repo

      - name: Init submodules
        run: |
          cd dlstreamer-repo
          git submodule update --init thirdparty/spdlog

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd #4.0.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 #4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build deb final img with cache from GHCR
        env:
          deb_final_img_cached: ghcr.io/${{ github.repository }}/deb-final-img-${{ matrix.ubuntu_version }}:buildcache
        run: |
          docker buildx build \
            --target dlstreamer \
            --cache-to=type=registry,ref=${deb_final_img_cached},mode=max \
            --cache-from=type=registry,ref=${deb_final_img_cached} \
            --build-arg DLSTREAMER_VERSION=${{ env.dlstreamer-version }} \
            --build-arg DLSTREAMER_BUILD_NUMBER=deb-pkg-${{ matrix.ubuntu_version }} \
            -f ${{ matrix.path_dockerfile }} \
            ${{ env.DLS_REL_PATH }}

      - name: Clean up
        if: always()
        run: |
          rm -rf dlstreamer-repo

  build-dls-dev-img:
    name: Build DLS ${{ matrix.ubuntu_version }} dev debug img
    runs-on: dlstreamer
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - path_dockerfile: ./dlstreamer-repo/docker/ubuntu/ubuntu22.Dockerfile
            ubuntu_version: ubuntu22
            build_arg: Debug
          - path_dockerfile: ./dlstreamer-repo/docker/ubuntu/ubuntu24.Dockerfile
            ubuntu_version: ubuntu24
            build_arg: Debug
    steps:
      - name: Check out dlstreamer repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2
        with:
          persist-credentials: false
          path: dlstreamer-repo

      - name: Init submodules
        run: |
          cd dlstreamer-repo
          git submodule update --init thirdparty/spdlog

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd #4.0.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 #4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build dev debug img with cache from GHCR
        env:
          dev_debug_img_cached: ghcr.io/${{ github.repository }}/dev-debug-img-${{ matrix.ubuntu_version }}:buildcache
        run: |
          docker buildx build \
            --target dlstreamer-dev \
            --cache-from=type=registry,ref=${dev_debug_img_cached} \
            --cache-to=type=registry,ref=${dev_debug_img_cached},mode=max \
            --build-arg BUILD_ARG=${{ matrix.build_arg }} \
            -f ${{ matrix.path_dockerfile }} \
            ${{ env.DLS_REL_PATH }}

      - name: Clean up
        if: always()
        run: |
          rm -rf dlstreamer-repo

  build-dls-fedora41-img:
    name: Build DLS Fedora 41 img
    runs-on: dlstreamer
    permissions:
      contents: read
      packages: write
    steps:
      - name: Initial environment clean
        run: |
          sudo rm -rf dlstreamer-repo

      - name: Check out dlstreamer repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #6.0.2
        with:
          persist-credentials: false
          path: dlstreamer-repo

      - name: Init submodules
        run: |
          cd dlstreamer-repo
          git submodule update --init thirdparty/spdlog

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd #4.0.0

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@b45d80f862d83dbcd57f89517bcf500b2ab88fb2 #4.0.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build f41 img with cache from GHCR
        env:
          f41_img_cached: ghcr.io/${{ github.repository }}/f41-img:buildcache
        run: |
          docker buildx build \
            --target dlstreamer \
            --cache-from=type=registry,ref=${f41_img_cached} \
            --cache-to=type=registry,ref=${f41_img_cached},mode=max \
            --build-arg DLSTREAMER_BUILD_NUMBER=${{ github.run_number }} \
            -f ./dlstreamer-repo/docker/fedora41/fedora41.Dockerfile \
            ${{ env.DLS_REL_PATH }}

      - name: Clean up
        if: always()
        run: |
          rm -rf dlstreamer-repo
